apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-deployment
  labels:
    app: web1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web1
  strategy: {}
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: app
          image: f3rrum/kubernetes_repo:nginx_kuber
          volumeMounts:
            - name: app
              mountPath: /app
      initContainers:
        - name: init-myservice
          image: busybox:1.31.0
          command: ["sh", "-c", "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          emptyDir: {}